server:
    interface: 0.0.0.0
    port: 53
    do-ip4: yes
    do-udp: yes
    do-tcp: yes
    access-control: 10.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow
    access-control: 192.168.0.0/16 allow
    verbosity: 1

    # Optional but recommended
    hide-identity: yes
    hide-version: yes

# Your zone
local-zone: "sddc.lab." static

local-data: "dns.sddc.lab A 192.168.12.121"
local-data-ptr: "192.168.12.121 dns.sddc.lab"

local-data: "host32.sddc.lab A 10.203.5.32"
local-data-ptr: "10.203.5.32 host32.sddc.lab"

local-data: "pod-240-vc01.sddc.lab A 10.203.240.10"
local-data-ptr: "10.203.240.10 pod-240-vc01.sddc.lab"

local-data: "pod-240-nsx01.sddc.lab A 10.203.240.11"
local-data-ptr: "10.203.240.11 pod-240-nsx01.sddc.lab"

local-data: "pod-240-nsx02.sddc.lab A 10.203.240.12"
local-data-ptr: "10.203.240.12 pod-240-nsx02.sddc.lab"

local-data: "pod-240-ops01.sddc.lab A 10.203.240.13"
local-data-ptr: "10.203.240.13 pod-240-ops01.sddc.lab"

local-data: "pod-240-collector.sddc.lab A 10.203.240.14"
local-data-ptr: "10.203.240.14 pod-240-collector.sddc.lab"

local-data: "pod-240-vsp01.sddc.lab A 10.203.240.15"
local-data-ptr: "10.203.240.15 pod-240-vsp01.sddc.lab"

local-data: "pod-240-sddcm.sddc.lab A 10.203.240.16"
local-data-ptr: "10.203.240.16 pod-240-sddcm.sddc.lab"

local-data: "pod-240-fleet01.sddc.lab A 10.203.240.17"
local-data-ptr: "10.203.240.17 pod-240-fleet01.sddc.lab"

local-data: "pod-240-int01.sddc.lab A 10.203.240.18"
local-data-ptr: "10.203.240.18 pod-240-int01.sddc.lab"

local-data: "pod-240-vidb.sddc.lab A 10.203.240.19"
local-data-ptr: "10.203.240.19 pod-240-vidb.sddc.lab"

local-data: "pod-240-auto.sddc.lab A 10.203.240.20"
local-data-ptr: "10.203.240.20 pod-240-auto.sddc.lab"

local-data: "pod-240-license.sddc.lab A 10.203.240.21"
local-data-ptr: "10.203.240.21 pod-240-license.sddc.lab"

local-data: "pod-240-autosvc.sddc.lab A 10.203.240.56"
local-data-ptr: "10.203.240.56 pod-240-autosvc.sddc.lab"

local-data: "pod-240-en1.sddc.lab A 10.203.240.57"
local-data-ptr: "10.203.240.57 pod-240-en1.sddc.lab"

local-data: "pod-240-en2.sddc.lab A 10.203.240.58"
local-data-ptr: "10.203.240.58 pod-240-en2.sddc.lab"

local-data: "idp.sddc.lab A 10.203.240.81"
local-data-ptr: "10.203.240.81 idp.sddc.lab"

local-data: "auth.sddc.lab A 192.168.12.121"
local-data-ptr: "192.168.12.121 auth.sddc.lab"

local-data: "pod-240-dsmva.sddc.lab A 10.203.240.91"
local-data-ptr: "10.203.240.91 pod-240-dsmva.sddc.lab"

forward-zone:
    name: "."
    forward-addr: 8.8.8.8