server 0.se.pool.ntp.org iburst
server 1.se.pool.ntp.org iburst
server 2.se.pool.ntp.org iburst

allow 10.0.0.0/8
allow 192.168.12.0/24

bindaddress 0.0.0.0
local stratum 10

driftfile /var/lib/chrony/drift
logdir /var/log/chrony
